server:
  port: 8020
spring:
  profiles:
    active: local
  application:
    name: jeep
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#搜索配置
  data:
    elasticsearch:
      cluster-name: elasticsearch_xianguo
      cluster-nodes: localhost
# 多数据源配置
  datasource:
      druid:
      # 测试环境没有主库和备库之分
        first:
          url: jdbc:mysql://localhost:3306/jeep_db?useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: alixian
          driver-class-name: com.mysql.jdbc.Driver
        second:
          url: jdbc:mysql://localhost:3306/moyu_db?useUnicode=true&characterEncoding=utf-8&useSSL=true
          username: root
          password: alixian
          driver-class-name: com.mysql.jdbc.Driver
#日志配置
logging:
  config: classpath:jeep-logback.xml

